#!/bin/sh

# Update files
git --work-tree=/var/www/on/graphene --git-dir=/var/repo/on/graphene checkout -f

cd /var/www/on/graphene

# Set permissions
chown -R www-data:www-data .
chmod -R 775 storage bootstrap/cache

# Install dependencies, run migrations, and build assets
COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev
php artisan migrate --force
npm ci && npm run production

# Set permissions again
chown -R www-data:www-data .
chmod -R 775 storage bootstrap/cache

